-- 코드를 입력하세요
# SELECT
# *
#     # A.PRODUCT_CODE
#     # , SALES
# FROM PRODUCT AS A
# JOIN OFFLINE_SALE AS B ON A.PRODUCT_ID = B.PRODUCT_ID


SELECT 
    B.PRODUCT_CODE
    , SUM(SALES_AMOUNT) * B.PRICE AS SALES
FROM OFFLINE_SALE AS A
JOIN PRODUCT AS B ON A.PRODUCT_ID = B.PRODUCT_ID
GROUP BY A.PRODUCT_ID
ORDER BY SALES DESC, B.PRODUCT_CODE ASC;