-- 코드를 입력하세요   
# SELECT
#     CAR_ID,
#     CAR_TYPE,
#     DAILY_FEE AS FEE
# FROM CAR_RENTAL_COMPANY_CAR
# WHERE CAR_TYPE = '세단' OR CAR_TYPE = 'SUV';

# SELECT
#     *
# FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
# WHERE DURATION_TYPE = '30일 이상';

# SELECT
#     *
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
# WHERE END_DATE < '2022-11-01' OR  START_DATE > '2022-11-30';

SELECT 
    C.CAR_ID,
    C.CAR_TYPE,
    ROUND(C.DAILY_FEE * (100 - D.DISCOUNT_RATE) / 100) * 30 AS FEE
FROM CAR_RENTAL_COMPANY_CAR AS C
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS D
    ON C.CAR_TYPE = D.CAR_TYPE
    AND D.DURATION_TYPE = '30일 이상'
WHERE (C.CAR_TYPE = '세단' OR C.CAR_TYPE = 'SUV')
  AND C.CAR_ID NOT IN (
      SELECT CAR_ID
      FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
      WHERE NOT (END_DATE < '2022-11-01' OR START_DATE > '2022-11-30')
  )
HAVING FEE >= 500000 AND FEE < 2000000
ORDER BY FEE DESC, C.CAR_TYPE ASC, C.CAR_ID DESC;
