-- 코드를 입력하세요
SELECT
    A.NAME,
    A.DATETIME
FROM ANIMAL_INS AS A
WHERE A.ANIMAL_ID NOT IN (
    SELECT
        C.ANIMAL_ID
    FROM ANIMAL_OUTS AS C
    INNER JOIN ANIMAL_INS AS D ON C.ANIMAL_ID = D.ANIMAL_ID
)
ORDER BY A.DATETIME ASC
LIMIT 3;

