-- 코드를 입력하세요
SELECT
    A.PRODUCT_ID
    , A.PRODUCT_NAME
    , B.TOTAL_AMOUNT * A.PRICE AS TOTAL_SALES
FROM FOOD_PRODUCT AS A
JOIN (
    SELECT 
        PRODUCT_ID
        , PRODUCE_DATE
        , SUM(AMOUNT) AS 'TOTAL_AMOUNT'
    FROM FOOD_ORDER
    WHERE YEAR(PRODUCE_DATE) = 2022 AND MONTH(PRODUCE_DATE) = 05
    GROUP BY PRODUCT_ID
    ORDER BY PRODUCT_ID
) AS B ON A.PRODUCT_ID = B.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, A.PRODUCT_ID;


