-- 코드를 입력하세요
SELECT
    A.MEMBER_NAME
    , B.REVIEW_TEXT
    , DATE_FORMAT(B.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM MEMBER_PROFILE AS A
JOIN REST_REVIEW AS B 
  ON A.MEMBER_ID = B.MEMBER_ID
WHERE A.MEMBER_ID = (
        SELECT
            MEMBER_ID
        FROM REST_REVIEW 
        GROUP BY MEMBER_ID
        ORDER BY COUNT(REVIEW_ID) DESC
        LIMIT 1
    )
ORDER BY REVIEW_DATE ASC, REVIEW_TEXT ASC;

# SELECT
#     *
# FROM REST_REVIEW AS C
# JOIN (
#     SELECT
#         MEMBER_ID
#         , COUNT(MEMBER_ID) AS 'COUNT_REVIEW'
#     FROM REST_REVIEW 
#     GROUP BY MEMBER_ID
# ) AS D 
# ON C.MEMBER_ID = D.MEMBER_ID
# ORDER BY D.COUNT_REVIEW DESC


# SELECT
#     MEMBER_ID
# FROM REST_REVIEW 
# GROUP BY MEMBER_ID
# ORDER BY COUNT(REVIEW_ID) DESC
# LIMIT 1